namespace * ophan.thrift.event
namespace cocoa GLAOphanThriftEvent

/**
* Differentiates between the (many) different types of print product
**/
enum PrintProduct {

    VOUCHER_SATURDAY = 1

    VOUCHER_SATURDAY_PLUS = 2

    VOUCHER_WEEKLY_AND_SATURDAY = 3

    VOUCHER_WEEKLY_AND_SATURDAY_PLUS = 4

    VOUCHER_SUNDAY = 5

    VOUCHER_SUNDAY_PLUS = 6

    /**
    * DEPRECATED DO NOT USE
    * This enum has a spelling mistake. Use VOUCHER_WEEKEND (27) instead
    **/
    VOUCER_WEEKEND = 7

    /**
    * DEPRECATED DO NOT USE
    * This enum has a spelling mistake. Use VOUCHER_WEEKEND_PLUS (28) instead
    **/
    VOUCER_WEEKEND_PLUS = 8

    VOUCHER_SIXDAY = 9

    VOUCHER_SIXDAY_PLUS = 10

    VOUCHER_EVERYDAY = 11

    VOUCHER_EVERYDAY_PLUS = 12

    HOME_DELIVERY_SATURDAY = 13

    HOME_DELIVERY_SATURDAY_PLUS = 14

    HOME_DELIVERY_WEEKLY_AND_SATURDAY = 15

    HOME_DELIVERY_WEEKLY_AND_SATURDAY_PLUS = 16

    HOME_DELIVERY_SUNDAY = 17

    HOME_DELIVERY_SUNDAY_PLUS = 18

    HOME_DELIVERY_WEEKEND = 19

    HOME_DELIVERY_WEEKEND_PLUS = 20

    HOME_DELIVERY_SIXDAY = 21

    HOME_DELIVERY_SIXDAY_PLUS = 22

    HOME_DELIVERY_EVERYDAY = 23

    HOME_DELIVERY_EVERYDAY_PLUS = 24

    GUARDIAN_WEEKLY = 25

    GUARDIAN_WEEKLY_PLUS = 26

    VOUCHER_WEEKEND = 27

    VOUCHER_WEEKEND_PLUS = 28
}